"use client"

import React from "react"
import { motion } from "framer-motion"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Mitig8Logo } from "@/components/mitig8-logo"

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using CureAtHub, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our platform. These terms apply to all users, including visitors, registered members, and healthcare professionals who access the service.`,
  },
  {
    title: "2. About CureAtHub",
    content: `CureAtHub is an AI-powered health monitoring and prediction platform designed to assist individuals in understanding health-related data and trends. The platform provides informational tools and insights to help users make more informed decisions about their health. CureAtHub is not a licensed medical provider and does not offer medical diagnosis, treatment, or clinical advice. All outputs generated by the platform are for informational and educational purposes only.`,
  },
  {
    title: "3. Eligibility",
    content: `You must be at least 18 years of age to create an account and use CureAtHub. By registering, you represent that you are of legal age and have the legal capacity to enter into a binding agreement. If you are accessing the platform on behalf of a minor, you take full responsibility for their use and for ensuring that the use complies with applicable laws.`,
  },
  {
    title: "4. User Accounts",
    content: `When you create an account on CureAtHub, you are responsible for maintaining the confidentiality of your login credentials. You agree to provide accurate, current, and complete information during registration and to update this information as needed. You are responsible for all activity that occurs under your account. If you believe your account has been accessed without authorization, you must notify us immediately. CureAtHub reserves the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: "5. Health Information Disclaimer",
    content: `The health data, predictions, and insights provided by CureAtHub are generated by artificial intelligence and are not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional before making any decisions about your health, medication, or treatment plans. CureAtHub does not take responsibility for any health outcomes resulting from reliance on information provided through the platform. Do not disregard or delay seeking medical advice because of something you have read or seen on CureAtHub.`,
  },
  {
    title: "6. Acceptable Use",
    content: `You agree to use CureAtHub only for lawful purposes and in a way that does not infringe the rights of others. You must not use the platform to upload or distribute harmful, fraudulent, or misleading health information. You must not attempt to access the accounts of other users or attempt to reverse-engineer, decompile, or interfere with the platform's systems or infrastructure. Any misuse of the platform may result in immediate termination of your account without notice.`,
  },
  {
    title: "7. Intellectual Property",
    content: `All content on CureAtHub, including but not limited to text, graphics, logos, user interface elements, and AI model outputs, is the property of CureAtHub or its licensors. You may not reproduce, copy, distribute, or create derivative works from any part of the platform without our express written consent. You retain ownership of health data you upload to the platform, but by doing so, you grant CureAtHub a limited license to process and analyze that data in order to provide the service to you.`,
  },
  {
    title: "8. Data and Privacy",
    content: `Your privacy matters to us. How we collect, store, and use your personal and health information is explained in detail in our Privacy Policy, which forms part of these Terms of Service. By using CureAtHub, you also agree to our Privacy Policy. We recommend reading it carefully before using the platform.`,
  },
  {
    title: "9. Changes to the Service",
    content: `CureAtHub reserves the right to modify, suspend, or discontinue any aspect of the service at any time, with or without prior notice. We may also update these Terms of Service from time to time. When we make significant changes, we will notify you through the platform or via email. Your continued use of the platform after changes have been made constitutes your acceptance of the updated terms.`,
  },
  {
    title: "10. Limitation of Liability",
    content: `To the fullest extent permitted by applicable law, CureAtHub shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of data, loss of profits, or health-related outcomes, arising out of your use of or inability to use the platform. Our total liability to you for any claim shall not exceed the amount you paid to use the service in the twelve months prior to the claim.`,
  },
  {
    title: "11. Termination",
    content: `Either party may terminate the user relationship at any time. You may close your account by contacting our support team. CureAtHub may suspend or permanently terminate your account if you violate these terms or engage in conduct that we determine to be harmful to other users or to the platform. Upon termination, your right to access the service will cease immediately.`,
  },
  {
    title: "12. Governing Law",
    content: `These Terms of Service shall be governed by and construed in accordance with the laws of India. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the courts located in India. If any provision of these terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.`,
  },
  {
    title: "13. Contact Us",
    content: `If you have questions, concerns, or feedback regarding these Terms of Service, please reach out to our team. We are committed to addressing your queries in a timely and transparent manner. You can contact us at support@cureathub.com. We typically respond within 2 to 3 business days.`,
  },
]

export function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FDF6EE] relative overflow-hidden">
      <div
        className="absolute inset-0 opacity-[0.025]"
        style={{
          backgroundImage: "radial-gradient(circle at 1px 1px, #C4A882 1px, transparent 0)",
          backgroundSize: "48px 48px",
        }}
      />

      <div className="relative z-10 max-w-3xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-10"
        >
          <Link
            href="/auth"
            className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-orange-600 transition-colors group"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            Back
          </Link>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="mb-10"
        >
          <Mitig8Logo size="lg" theme="dark" animated={false} />
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, type: "spring", stiffness: 100, damping: 18 }}
          className="bg-white/80 backdrop-blur-xl border border-white/60 rounded-3xl shadow-2xl shadow-orange-500/[0.06] p-8 md:p-12"
        >
          <div className="mb-10">
            <h1 className="text-3xl font-bold text-[#0F172A] mb-3">Terms of Service</h1>
            <p className="text-sm text-slate-500">
              Last updated: June 12, 2025
            </p>
            <div className="mt-5 p-4 bg-orange-50 border border-orange-100 rounded-xl">
              <p className="text-sm text-slate-600 leading-relaxed">
                Please read these Terms of Service carefully before using CureAtHub. They explain your rights and
                responsibilities as a user of our platform. By creating an account or continuing to use the service, you
                agree to be bound by these terms.
              </p>
            </div>
          </div>

          <div className="space-y-8">
            {sections.map((section, index) => (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.25 + index * 0.04 }}
              >
                <h2 className="text-base font-bold text-[#0F172A] mb-2">{section.title}</h2>
                <p className="text-sm text-slate-600 leading-7">{section.content}</p>
                {index < sections.length - 1 && (
                  <div className="mt-8 h-px bg-slate-100" />
                )}
              </motion.div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-xs text-slate-400">
              These terms were last reviewed and updated on June 12, 2025.
            </p>
            <Link
              href="/privacy"
              className="text-sm font-semibold text-orange-600 hover:text-orange-700 transition-colors hover:underline"
            >
              Read Privacy Policy
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
